server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;

    location = /TINAapimed {
        return 301 /TINAapimed/;
    }

    location /TINAapimed/api/ {
        proxy_request_buffering off;
        client_body_buffer_size 16m;
        client_max_body_size 20m;
        proxy_pass http://backend:8000/api/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /TINAapimed/ {
        rewrite ^/TINAapimed/(.*)$ /$1 break;
        try_files $uri $uri/ /index.html;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
